package org.example;

public class Enrollment {
    private int id; // This might be auto-generated by the database
    private int studentId; // This links to the student
    private int courseId; // This links to the course

    // Constructor for creating a new Enrollment without an ID
    public Enrollment(int studentId, int courseId) {
        this.studentId = studentId;
        this.courseId = courseId;
    }

    // Constructor for creating an Enrollment with an ID (e.g., when retrieving from the database)
    public Enrollment(int id, int studentId, int courseId) {
        this.id = id;
        this.studentId = studentId;
        this.courseId = courseId;
    }

    // Getters
    public int getId() {
        return id;
    }

    public int getStudentId() {
        return studentId;
    }

    public int getCourseId() {
        return courseId;
    }

    // Optionally, you can add setters if you need to modify these fields
    public void setId(int id) {
        this.id = id;
    }

    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
}